// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

// ignore_for_file: non_constant_identifier_names

import 'dart:ffi';

import 'bridge_generated.dart';

// Re-export the bridge so it is only necessary to import this file.
export 'bridge_generated.dart';

const _libName = 'lib_kmeans.so';
final KMeansRustImpl FFI_PORTAL = KMeansRustImpl(
  DynamicLibrary.open(_libName),
);
