name: k_means_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  meta: ^1.8.0
  lints: ^2.0.0
  flutter_rust_bridge: ^1.41.1
  test: ^1.21.4
  vm_service: ^9.0.0
  freezed_annotation: ^2.1.0
  ffi: ^2.0.1
dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  ffigen: ^6.0.1
